services:
  backend:
    build: .
    ports:
      - "5001:5000" # Changed host port to 5001 to resolve conflict
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/quickChatDB
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: quickchat-mongo
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"] # Bind MongoDB to all network interfaces
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data:
